"""Auto-Phone No:

Revision ID: 20ab2ffa8986
Revises: f4878b014894
Create Date: 2024-06-01 11:10:28.314990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20ab2ffa8986'
down_revision: Union[str, None] = 'f4878b014894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('phone_no', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.drop_column('posts', 'phone_no')
    # ### end Alembic commands ###
